# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_NEW: [ ROLE_USER ]
        ROLE_SUPER_BACK_OFFICE: [ ROLE_USER, ROLE_BACK_OFFICE , ROLE_SONATA_ADMIN, ROLE_SELLS, ROLE_SUPER_SELLS ]
        ROLE_MONEY_ADMIN: [ ROLE_USER, ROLE_MONEY_ADMIN ]
        ROLE_BACK_OFFICE: [ ROLE_USER, ROLE_BACK_OFFICE ]
        ROLE_SUPER_SELLS: [ ROLE_USER, ROLE_SELLS, ROLE_SUPER_SELLS ]
        ROLE_ADMIN:       [ ROLE_USER , ROLE_SONATA_ADMIN ]
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN , ROLE_ALLOWED_TO_SWITCH ]


    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        #d# in_memory:
        #d#    memory: ~
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        wsse_secured:
            pattern:   ^/api/secured/.*
            stateless: true
            wsse:      { lifetime: 3000000 }
            #anonymous:    true
    #    remember_me:
    #        key:      symplifica
    #        lifetime: 604800
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
                always_use_default_target_path: false
                default_target_path: /pages
                success_handler: authentication_handler
                failure_handler: authentication_handler
            oauth:
                failure_path: fos_user_registration_register
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: welcome_post_register
                provider: fos_userbundle
                resource_owners:
                    facebook: hwi_facebook_login
                    google: hwi_google_login
                    linkedin: hwi_linkedin_login
                oauth_user_provider:
                    #this is my custom user provider, created from FOSUBUserProvider - will manage the
                    #automatic user registration on your site, with data from the provider (facebook. google, etc.)
                    service: my_user_provider

            anonymous:    true
            logout:
                path:           fos_user_security_logout
                target:         home_landing
                #where to go after logout
            #d# anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
        - { path: ^/admin.*, roles: [ROLE_ADMIN , ROLE_BACK_OFFICE] }
        - { path: ^/backoffice.*, roles: ROLE_BACK_OFFICE }
        - { path: ^/ventas/*, roles: ROLE_SELLS}
        - { path: ^/administrador.*, roles: ROLE_MONEY_ADMIN}
        - { path: ^/media.*, roles: ROLE_BACK_OFFICE }

        - { path: ^/add.*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/change-flag.*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/choose.*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/contract.*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/datacredit.*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/dashboard.*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/daviplata.*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/document.*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/download.*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/edit/.*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/entity.*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/employee.*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/employer.*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/express.*, roles: ROLE_BACK_OFFICE }
        - { path: ^/export.*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/help.*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/invitation.*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/legal-status.*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/legal-payment.*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/legal-assist.*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/legal-acceptance.*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/liquidation.*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/logs.*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/matrix.*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/manage.*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/notifications.*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/novelty.*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/nosotros-back.*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/ordenes.*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/old.*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/pages.*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/protest.*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/paymentmethod.*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/pay.*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/pdf.*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/welcome.*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/registration.*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/register/contract/.*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/remove.*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/routes.*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/send-email.*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/settings.*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/subscription.*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/subscripcion.*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/user.*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/usuario.*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/view.*, roles: IS_AUTHENTICATED_FULLY }



        # Web services access.
        # 190.7.130.163, is the symplifica office ip.
        # 181.143.94.42, is the multiplica office ip.
        # 52.73.123.224 is the real amazon server.
        # 52.91.121.67 is the symplifica development server.
        # 190.24.91.37 is the ip office of hightech.
        # 52.86.183.212 is the ip of production hightech.
        # cpsuite.htsoft.co is the hightech server host.

        # This are the web services for hightech, they should be before the normal web services.
        - { path: ^/api/public/v1/notificacion, role: IS_AUTHENTICATED_ANONYMOUSLY, ips: [10.0.0.1, 127.0.0.1, 190.7.130.163, 52.73.123.224, 52.91.121.67, 190.24.91.37, 52.86.183.212, 172.16.1.11] }
        - { path: ^/api/public/v1/notificacion, role: IS_AUTHENTICATED_ANONYMOUSLY, host: cpsuite\.htsoft\.co$ }
        - { path: ^/api/public/v1/notificacion, role: [ROLE_NO_ACCESS] }

        # This are the web services for novopayment, they should be before the normal web services.
        - { path: ^/api/public/v1/dispersion/[0-9]+$, role: IS_AUTHENTICATED_ANONYMOUSLY, ips: [10.0.0.1, 127.0.0.1, 190.7.130.163, 52.73.123.224, 52.91.121.67 ] }
        - { path: ^/api/public/v1/dispersion/[0-9]+$, role: IS_AUTHENTICATED_ANONYMOUSLY, ips: [72.46.255.110] }
        - { path: ^/api/public/v1/dispersion/[0-9]+$, role: [ROLE_NO_ACCESS] }

        # This two next lines are used to allow access to those ips, in any service.
        - { path: ^/api/public/v1/secured, role: IS_AUTHENTICATED_ANONYMOUSLY, ips: [10.0.0.1, 127.0.0.1, 190.7.130.163, 52.73.123.224, 52.91.121.67] }
        - { path: ^/api/public/v1/secured, role: [ROLE_NO_ACCESS] }
        - { path: ^/novelty/workableDays/validateandpersist/^, role: IS_AUTHENTICATED_ANONYMOUSLY, ips: [10.0.0.1, 127.0.0.1, 190.7.130.163, 52.73.123.224, 52.91.121.67] }
