rocket_seller_two_pick_invitation:
    resource: "@RocketSellerTwoPickBundle/Resources/config/routing/invitation.yml"
    prefix:   /invitation
rocket_seller_two_pick_documents:
    resource: "@RocketSellerTwoPickBundle/Resources/config/routing/document.yml"
    prefix:   /documents
rocket_seller_two_pick_liquidation:
    resource: "@RocketSellerTwoPickBundle/Resources/config/routing/liquidation.yml"
    prefix:   /liquidations
rocket_seller_two_pick_homepage:
    path:     /old
    defaults: { _controller: RocketSellerTwoPickBundle:Default:index }
procedure_test:
    path:     /protest
    defaults: { _controller: RocketSellerTwoPickBundle:Procedure:testValidate }
payments_method:
    path:     /paymentmethod/{idNotification}
    defaults: { _controller: RocketSellerTwoPickBundle:PaymentMethod:index, idNotification: -1 }
show_email_groups:
    path:     /backoffice/email/groups/info
    defaults: { _controller: RocketSellerTwoPickBundle:BackOffice:emailGroupView }
show_calendar_info:
    path:     /backoffice/calendar/info
    defaults: { _controller: RocketSellerTwoPickBundle:BackOffice:fullTimeCalendarView }
change_contracts:
    path:     /backoffice/change/contracts/info/{contract}/{documentType}/{document}/{email}/{index}
    defaults: { _controller: RocketSellerTwoPickBundle:BackOffice:modifyContractsView, contract: '',documentType: '',document: '',email: '',index: 1 }
show_novelties_info:
    path:     /backoffice/novelty/info/{name}/{lastName}/{contract}/{documentType}/{document}/{email}/{index}
    defaults: { _controller: RocketSellerTwoPickBundle:BackOffice:modifyNoveltiesInfo, name: '', lastName: '',contract: '',documentType: '',document: '',email: '',index: 1 }
modify_payroll:
    path:     /backoffice/modify/payroll/{idPayroll}/{noveltiesHadChanged}/{executed}
    defaults: { _controller: RocketSellerTwoPickBundle:BackOffice:modifyPayroll,idPairoll: 0,noveltiesHadChanged: false, executed: false }
delete_novelty:
    path:     /backoffice/delete/novelty/{idPayroll}/{idNovelty}
    defaults: { _controller: RocketSellerTwoPickBundle:BackOffice:deleteNovelty,idPairoll: 0,idNovelty: 0 }

#Payments
show_payments:
    path: /show/payments/{id}
    defaults: { _controller: RocketSellerTwoPickBundle:Pay:showPayments }
show_pay_detail:
    path: /show/pay/{id}
    defaults: { _controller: RocketSellerTwoPickBundle:Pay:viewPayDetail }
_nosotros:
    path:     /nosotros-back
    defaults: { _controller: RocketSellerTwoPickBundle:CorporatePages:Nosotros }

terminos_condiciones:
    path:     /terminos-condiciones
    defaults: { _controller: RocketSellerTwoPickBundle:CorporatePages:terminosCondiciones }

politica_privacidad:
    path:     /politica-privacidad
    defaults: { _controller: RocketSellerTwoPickBundle:CorporatePages:politicaPrivacidad }
intro_sin_verificar:
    path: /verificar-cuenta
    defaults: { _controller: RocketSellerTwoPickBundle:Default:introSinVerificar }
routes:
    path:     /routes
    defaults: { _controller: RocketSellerTwoPickBundle:Default:getAllRoutes }

#Back Office SELLS
sells_dashboard:
    path:     /ventas
    defaults: { _controller: RocketSellerTwoPickBundle:SellsBackOffice:index}
#Back Office
back_office:
    path:     /backoffice
    defaults: { _controller: RocketSellerTwoPickBundle:BackOffice:index}
back_office_prima:
    path:     /backoffice/add/prima
    defaults: { _controller: RocketSellerTwoPickBundle:BackOffice:addPrima}
show_procedures:
    path:     /backoffice/procedures/{orderType}/{order}/{state}/{document}/{names}/{prior}
    defaults: { _controller: RocketSellerTwoPickBundle:Procedure:index,orderType: 'none',order: 'ASC',state: 'none',document: 'none',names: 'none',prior: 'none'}
show_request:
    path:     /backoffice/request
    defaults: { _controller: RocketSellerTwoPickBundle:BackOffice:showRequest}
legal_ass:
    path:     /backoffice/legal
    defaults: { _controller: RocketSellerTwoPickBundle:BackOffice:legalAssistance}
register_express:
    path:     /backoffice/register
    defaults: { _controller: RocketSellerTwoPickBundle:BackOffice:registerExpress}
marketing:
    path:     /backoffice/marketing
    defaults: { _controller: RocketSellerTwoPickBundle:BackOffice:showLanding}
express_back:
    path:     /backoffice/marketing/express/{id}
    defaults: { _controller: RocketSellerTwoPickBundle:BackOffice:showExpress, id: -1}

#security break
autenticate:
    path:     /backoffice/autenticate/{user}/{autentication}
    defaults: { _controller: RocketSellerTwoPickBundle:BackOffice:demoLogin}
users_login_back:
    path:     /backoffice/show/users/autenticate
    defaults: { _controller: RocketSellerTwoPickBundle:BackOffice:showUsersLogin}

#backoffice reports
show_rejected_pods:
    path:     /backoffice/show/rejected/pods
    defaults: { _controller: RocketSellerTwoPickBundle:BackOffice:showRejectedPOD}
back_retry_pay_po:
    path:     /backoffice/back/retry/pay/{idPO}
    defaults: { _controller: RocketSellerTwoPickBundle:BackOffice:retryPay}
back_retry_pay_pod:
    path:     /backoffice/back/retry/pay/pod/{idPOD}
    defaults: { _controller: RocketSellerTwoPickBundle:BackOffice:retryPayPOD}
back_return_pay_pod:
    path:     /backoffice/back/return/pay/{idPOD}
    defaults: { _controller: RocketSellerTwoPickBundle:BackOffice:returnMoneyPay}
show_unfinished_users:
    path:     /backoffice/show/unfinished/users
    defaults: { _controller: RocketSellerTwoPickBundle:BackOffice:showUnfinishedUsers}
show_base_users_register:
    path:     /backoffice/show/base/users/register
    defaults: { _controller: RocketSellerTwoPickBundle:BackOffice:showBaseRegisterUsers}
show_successful_invoices:
    path:     /backoffice/show/successful/invoices/{year}/{month}
    defaults: { _controller: RocketSellerTwoPickBundle:BackOffice:showSuccessfulInvoices}
show_have_to_pay_users:
    path:     /backoffice/show/havetopay/users
    defaults: { _controller: RocketSellerTwoPickBundle:BackOffice:showHaveToPayUsers}
add_to_sql_and_hightec_back:
    path:     /backoffice/addtoback/{user}/{autentication}
    defaults: { _controller: RocketSellerTwoPickBundle:BackOffice:addToSQLandHighTecBack}
add_to_novo_back:
    path:     /backoffice/addtoback/{user}/{autentication}
    defaults: { _controller: RocketSellerTwoPickBundle:BackOffice:addToNovoBack}
add_to_sql_entities_back:
    path:     /backoffice/entities/addtoback/{user}/{autentication}/{idEhe}
    defaults: { _controller: RocketSellerTwoPickBundle:BackOffice:addToSQLEntitiesBack}
show_un_active_codes:
    path:     /backoffice/show/unactive/codes
    defaults: { _controller: RocketSellerTwoPickBundle:BackOffice:showUnActiveCodes}
generate_codes:
    path:     /backoffice/generate/codes/{amount}
    defaults: { _controller: RocketSellerTwoPickBundle:BackOffice:generateCodes}
show_pilas:
    path:     /backoffice/show/pilas
    defaults: { _controller: RocketSellerTwoPickBundle:PurchaseOrdersDescription:index}
persist_planilla_id:
    path:     /backoffice/planilla/persista/{fileName}/{idPod}/{payFile}
    defaults: { _controller: RocketSellerTwoPickBundle:PurchaseOrdersDescription:persistPilaEnlaceOperativoCode}
add_planilla_type_to_contracts:
    path:     /backoffice/planillaType/addtoback/{autentication}
    defaults: { _controller: RocketSellerTwoPickBundle:BackOffice:addPlanillaTypeToContractsBack}
clear_data_after_backup:
    path:     /backoffice/clearData/{autentication}
    defaults: { _controller: RocketSellerTwoPickBundle:BackOffice:clearDataAfterBackup}
user_view:
    path:     /backoffice/userView/{name}/{lastName}/{documentType}/{document}/{email}/{highTech}/{sql}/{ehe}/{pay}/{phone}/{contract}/{period}/{paid}/{join}/{index}
    defaults: { _controller: RocketSellerTwoPickBundle:BackOffice:userView, name: '', lastName: '',documentType: '',document: '',email: '',highTech: '', sql: '',ehe: '',pay: '',phone: '',contract: '',period: '',paid: '',join: '',index: 1}
post_register:
    path:     /backoffice/show/postRegister
    defaults: { _controller: RocketSellerTwoPickBundle:BackOffice:showPostRegisterEmployees}
employer_state:
    path:     /backoffice/show/employersState
    defaults: { _controller: RocketSellerTwoPickBundle:BackOffice:userBackOfficeState}
generate_report:
    path:     /backoffice/generate/report/{type}
    defaults: { _controller: RocketSellerTwoPickBundle:BackOffice:generateReportByType, type: null }
#tramites
create_procedures:
    path: /backoffice/procedure/creates/{userId}
    defaults: {_controller: RocketSellerTwoPickBundle:Procedure:procedure , userId: 0}
show_procedure:
    path:     /backoffice/procedure/{procedureId}
    defaults: { _controller: RocketSellerTwoPickBundle:Procedure:procedureById }
finish_action:
    path:         /backoffice/action/{actionId}/finish
    defaults:     { _controller: RocketSellerTwoPickBundle:Procedure:finish }
activate_action:
    path:         /backoffice/action/{actionId}/activate
    defaults:     { _controller: RocketSellerTwoPickBundle:Procedure:activate }
error_action:
    path:         /backoffice/action/{actionId}/error
    defaults:     { _controller: RocketSellerTwoPickBundle:Procedure:error }
activate_notification:
    path:         /backoffice/notification/{actionId}/{notificationId}/activate
    defaults:     { _controller: RocketSellerTwoPickBundle:Procedure:activateNotification }

#email test
back_test_email:
    path:         /backoffice/test/email
    defaults:     { _controller: RocketSellerTwoPickBundle:BackOffice:testEmail }

#export documents
export_documents_entity:
    path:         /entity/documents/export/{entityType}/{idEntity}
    defaults:     { _controller: RocketSellerTwoPickBundle:Export:exportDocuments , entityType : null , idEntity: -1 }
export_documents_person:
    path:         /backoffice/export/person/documents/{idPerson}
    defaults:     { _controller: RocketSellerTwoPickBundle:Export:exportDocumentsByPerson }
export_document_by_id:
    path:         /backoffice/export/document/{idDoc}
    defaults:     { _controller: RocketSellerTwoPickBundle:Export:exportDocumentByIdDocument, idDoc: -1}
export_contract:
    path:         /backoffice/export/employerHasEmployee/contract/{idContract}
    defaults:     {_controller: RocketSellerTwoPickBundle:Export:exportContract}
export_all_documents:
    path:         /backoffice/export/action/documents/{idAction}
    defaults:     { _controller: RocketSellerTwoPickBundle:Export:exportAllDocuments }
export_landing:
    path:         /backoffice/export/landing
    defaults:     { _controller: RocketSellerTwoPickBundle:Export:exportLanding }
back_person_cvs_export:
    path:         /backoffice/export/excel/{idAction}
    defaults:     { _controller: RocketSellerTwoPickBundle:Export:generateCsvByAction }


#empleador
send_info_validated:
    path:     /backoffice/info/validated/email/{procedureId}
    defaults: { _controller: RocketSellerTwoPickBundle:Procedure:sendEmployerInfoFinished}
send_info_error:
    path:     /backoffice/info/error/email/{procedureId}
    defaults: { _controller: RocketSellerTwoPickBundle:Procedure:sendEmployerInfoError}

#empleado
send_employee_info_error:
        path:     /backoffice/employee/info/error/email/{procedureId}/{eheId}
        defaults: { _controller: RocketSellerTwoPickBundle:Procedure:sendEmployeeInfoError}
send_employee_info_validated:
        path:     /backoffice/employee/info/validated/email/{procedureId}/{eheId}
        defaults: { _controller: RocketSellerTwoPickBundle:Procedure:sendEmployeeInfoFinished}
back_add_sql:
    path:         /backoffice/add/sql/{idEmployerHasEmployee}/{procedureId}
    defaults:     { _controller: RocketSellerTwoPickBundle:BackOffice:addToSQL }
complete_employee:
    path:         /backoffice/procedure/{procedureId}/complete/employee/{idEmployerHasEmployee}
    defaults:     { _controller: RocketSellerTwoPickBundle:Procedure:completeEmployee }
generate_contract:
    path:         /backoffice/generate/contract/{idEmployerHasEmployee}/{procedureId}
    defaults:     { _controller: RocketSellerTwoPickBundle:Procedure:generateContract }


validate_contract:
        path:     /backoffice/check/employee/contract/{idAction}
        defaults: { _controller: RocketSellerTwoPickBundle:BackOffice:validateContract}
change_action_status:
    path:         /backoffice/procedure/{procedureId}/{actionId}/{status}
    defaults:     { _controller: RocketSellerTwoPickBundle:Procedure:changeVueltaState }


back_employer_menu:
    path:         /backoffice/employer/menu/{id}
    defaults:     { _controller: RocketSellerTwoPickBundle:ExpressRegistration:menuEmployer }
    defaults:     { _controller: RocketSellerTwoPickBundle:BackOffice:testEmail}
back_pending_vacations:
    path:         /backoffice/pending/{idEmployerHasEmployee}/vacations/{pendingDays}
    defaults:     { _controller: RocketSellerTwoPickBundle:BackOffice:addToSQLPendingVacations }
back_entities_view:
    path:         /backoffice/entidades
    defaults:     { _controller: RocketSellerTwoPickBundle:BackOffice:eheEntitiesView }
back_pay_state_view:
    path:         /backoffice/estado/pagos
    defaults:     { _controller: RocketSellerTwoPickBundle:BackOffice:notPaidView }
back_frequency_state_view:
    path:         /backoffice/frecuencia/pagos
    defaults:     { _controller: RocketSellerTwoPickBundle:BackOffice:payTypeInfoView }
back_pila_operator_state_view:
    path:         /backoffice/estado/afiliacion/pila
    defaults:     { _controller: RocketSellerTwoPickBundle:BackOffice:checkPilaOperatorState}
back_pila_state_register_update:
    path:         /backoffice/actualizar/afiliacion/pila/{idEmployer}
    defaults:     { _controller: RocketSellerTwoPickBundle:BackOffice:updateStateRegistrationPilaOperator}
export_error_pila_afiliation:
    path:         /backoffice/export/error/pila/inscription/{idTransaction}
    defaults:     { _controller: RocketSellerTwoPickBundle:BackOffice:exportPilaOperatorAfiliationError }
back_fix_pods:
    path:         /backoffice/fix/pod
    defaults:     { _controller: RocketSellerTwoPickBundle:BackOffice:fixPODPila }
back_add_employer_enlace_operativo:
    path:         /backoffice/pila/add/enlace/operativo/{idEmployer}
    defaults:     { _controller: RocketSellerTwoPickBundle:BackOffice:addEmployerToEnlaceOperativoBack}
back_load_files_enlace_operativo:
    path:         /backoffice/pila/load/file/enlace/operativo
    defaults:     { _controller: RocketSellerTwoPickBundle:BackOffice:sendPlanillaFileToEnlaceOperativoBack }
back_check_banks:
    path:         /backoffice/check/banks/ht
    defaults:     { _controller: RocketSellerTwoPickBundle:BackOffice:highTechCheck }
back_fix_notifications_pay_notificationid:
    path:         /backoffice/fix/notifications/pay/notificationid
    defaults:     { _controller: RocketSellerTwoPickBundle:BackOffice:fixNotificationPayNotificationId }
back_set_referidos_code:
    path:         /backoffice/set/referidos/code
    defaults:     { _controller: RocketSellerTwoPickBundle:BackOffice:setReferidosCode }
back_set_referidos_code_allready_in_promocode:
    path:         /backoffice/set/referidos/code/allready/in/promocode
    defaults:     { _controller: RocketSellerTwoPickBundle:BackOffice:setReferidosCodeActionAlreadyInPromoCode }
back_personal_info_view:
    path:         /backoffice/personal/info/view
    defaults:     { _controller: RocketSellerTwoPickBundle:BackOffice:personalInfoView }
back_upload_planilla_file:
    path:         /backoffice/upload/{idPod}/planilla
    defaults:     { _controller: RocketSellerTwoPickBundle:BackOffice:uploadFileUsingPilaBot }
back_download_planilla_log:
    path:         /backoffice/download/{podId}/planilla/log
    defaults:     { _controller: RocketSellerTwoPickBundle:BackOffice:downloadPlanillaLog }
back_fix_broken_pila_bot:
    path:         /backoffice/fix/broken/pila/bot
    defaults:     { _controller: RocketSellerTwoPickBundle:BackOffice:fixBrokenPilaBot }
back_set_supply_notifications:
    path:         /backoffice/set/supply/notifications/{month}/{year}
    defaults:     { _controller: RocketSellerTwoPickBundle:BackOffice:setSupplyNotifications }
back_prima_view:
    path:         /backoffice/prima/view
    defaults:     { _controller: RocketSellerTwoPickBundle:BackOffice:primaView }
